// Code generated by "stringer -type=Tile"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Empty-0]
	_ = x[Wall-1]
	_ = x[Block-2]
	_ = x[Paddle-3]
	_ = x[Ball-4]
}

const _Tile_name = "EmptyWallBlockPaddleBall"

var _Tile_index = [...]uint8{0, 5, 9, 14, 20, 24}

func (i Tile) String() string {
	if i < 0 || i >= Tile(len(_Tile_index)-1) {
		return "Tile(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Tile_name[_Tile_index[i]:_Tile_index[i+1]]
}
